baseURL = 'https://frssdesign.github.io/'
languageCode = 'en-us'
title = 'Forensic-Ready System System Design'

[params]
  linkTitle = 'FRSS Design'
  themeVariant = 'frss-dark'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
