baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Forensic-Ready System Design'

[params]
  linkTitle =  'FRS'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'